# Generated by Django 5.0 on 2024-02-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_books', '0007_alter_borrowbook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='book',
        ),
    ]
