# Generated by Django 5.0 on 2024-02-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_books', '0008_remove_borrowbook_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='user',
        ),
    ]
