# Generated by Django 5.0 on 2024-02-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_balance'),
        ('books', '0005_remove_books_account'),
        ('borrow_books', '0009_remove_borrowbook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.books'),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.useraccount'),
        ),
    ]
