# Generated by Django 5.0 on 2024-02-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_balance'),
        ('borrow_books', '0011_alter_borrowbook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='user_acc',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.useraccount'),
        ),
    ]
