# Generated by Django 5.0 on 2024-02-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_books', '0012_borrowbook_user_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='user',
        ),
    ]
