# Generated by Django 5.0 on 2024-02-04 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_books', '0013_remove_borrowbook_user'),
        ('transactions', '0003_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='balance_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transactions'),
        ),
    ]
