# Generated by Django 5.0 on 2024-02-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_books', '0017_remove_borrowbook_balance_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='balance_transaction',
        ),
    ]
