# Generated by Django 5.0 on 2024-01-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_no',
            field=models.IntegerField(default=10001, unique=True),
            preserve_default=False,
        ),
    ]
