# Generated by Django 5.0 on 2024-02-03 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_balance'),
        ('books', '0003_books_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='account.useraccount'),
        ),
    ]
