# Generated by Django 5.0 on 2024-02-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='account',
        ),
    ]
