# Generated by Django 5.0 on 2024-02-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_comment_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=10),
        ),
    ]
