# Generated by Django 5.0 on 2024-02-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
